### ISSUE TITLE
Flatpak manifest

### ISSUE THREAD

**Issue by JakobDev** [Cubitect/cubiomes-viewer#139]
I got some free time and I was boring, so I created a Flatpak manifest for cubiomes-viewer:
```yaml
app-id: com.github.cubitect.cubiomes-viewer
runtime: org.kde.Platform
runtime-version: "5.15-21.08"
sdk: org.kde.Sdk
command: cubiomes-viewer
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --share=ipc

modules:
  - name: cubiomes-viewer
    buildsystem: qmake
    post-install:
      - install -Dm755 cubiomes-viewer /app/bin/cubiomes-viewer
      - install -Dm644 etc/com.github.cubitect.cubiomes-viewer.desktop /app/share/applications/com.github.cubitect.cubiomes-viewer.desktop
    sources:
      - type: archive
        url: https://github.com/Cubitect/cubiomes-viewer/releases/download/2.2.2/cubiomes-viewer-2.2.2-src.tar.gz
        sha256: 8eeb68c96c11b299a3a997ef5bb2bea417e47e195d7d942db07cdf3f93d24adc
    cleanup:
      - /lib
```
Save it as com.github.cubitect.cubiomes-viewer.yaml and build with:
```
flatpak-builder --user --install --force-clean build-dir com.github.cubitect.cubiomes-viewer.yaml
```
Now you can run it from the Menu.

The program itself works without problems, but there are still a few things to do:

- The icon have to be a supported size (see /usr/share/icons/hicolor for all supported sizes) and at least 128x128 or a SVG.
- You need screenshots
- You need a metainfo file
